# Generated by Django 5.1.4 on 2026-08-06 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='e-mail')),
                ('name', models.CharField(blank=True, max_length=160, verbose_name='nome')),
                ('status', models.CharField(choices=[('pending', 'Aguardando confirmação'), ('confirmed', 'Confirmado'), ('unsubscribed', 'Descadastrado')], db_index=True, default='pending', max_length=14, verbose_name='situação')),
                ('token', models.CharField(editable=False, max_length=64, unique=True, verbose_name='token')),
                ('consent_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP do consentimento')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='confirmado em')),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True, verbose_name='descadastrado em')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='cadastrado em')),
            ],
            options={
                'verbose_name': 'inscrito',
                'verbose_name_plural': 'inscritos',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=250, verbose_name='assunto')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='enviada em')),
                ('recipients', models.PositiveIntegerField(default=0, verbose_name='destinatários')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='blog.post', verbose_name='publicação')),
            ],
            options={
                'verbose_name': 'campanha',
                'verbose_name_plural': 'campanhas',
                'ordering': ['-created'],
            },
        ),
    ]
