# Generated by Django 5.1.4 on 2026-08-06 16:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='nome')),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('active', models.BooleanField(default=True, verbose_name='ativa')),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='nome')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=160, verbose_name='nome de exibição')),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True, verbose_name='slug')),
                ('credential', models.CharField(blank=True, help_text='Ex.: CRM-MT 4687 / RQE 2756', max_length=120, verbose_name='registro profissional')),
                ('specialty', models.CharField(blank=True, max_length=160, verbose_name='especialidade')),
                ('bio', models.TextField(blank=True, verbose_name='minicurrículo')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='autores/', verbose_name='foto')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail público')),
                ('active', models.BooleanField(default=True, verbose_name='ativo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('user', models.OneToOneField(blank=True, help_text='Conta usada para login. Deixe em branco para autor sem acesso ao painel.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author_profile', to=settings.AUTH_USER_MODEL, verbose_name='conta de acesso')),
            ],
            options={
                'verbose_name': 'autor',
                'verbose_name_plural': 'autores',
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220, verbose_name='título')),
                ('slug', models.SlugField(blank=True, max_length=240, unique=True, verbose_name='slug')),
                ('excerpt', models.TextField(help_text='Resumo exibido na listagem e no e-mail da newsletter.', max_length=400, verbose_name='breve descrição')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='imagem de capa')),
                ('cover_alt', models.CharField(blank=True, help_text='Descrição da imagem para acessibilidade e SEO.', max_length=200, verbose_name='texto alternativo da imagem')),
                ('published_at', models.DateTimeField(blank=True, help_text="Data futura + status 'Agendado' publica automaticamente.", null=True, verbose_name='data de publicação')),
                ('content', models.TextField(verbose_name='conteúdo')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('scheduled', 'Agendado'), ('published', 'Publicado')], db_index=True, default='draft', max_length=12, verbose_name='situação')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='título SEO')),
                ('meta_description', models.CharField(blank=True, max_length=300, verbose_name='descrição SEO')),
                ('newsletter_sent_at', models.DateTimeField(blank=True, editable=False, help_text='Preenchido automaticamente. Garante que o post não seja notificado duas vezes.', null=True, verbose_name='newsletter enviada em')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='blog.author', verbose_name='autor')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='blog.category', verbose_name='categoria')),
                ('tags', models.ManyToManyField(blank=True, related_name='posts', to='blog.tag', verbose_name='tags')),
            ],
            options={
                'verbose_name': 'publicação',
                'verbose_name_plural': 'publicações',
                'ordering': ['-published_at', '-created'],
                'indexes': [models.Index(fields=['status', 'published_at'], name='blog_post_status_5b2843_idx'), models.Index(fields=['slug'], name='blog_post_slug_cdb902_idx')],
            },
        ),
    ]
